### ISSUE TITLE
Criar CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by o-leolleo** [Gabrielr2508/recruitment-platform#3]
Essa issue tem a intenção de adicionar ao projeto o arquivo `CODE_OF_CONDUCT.md` para estabelecer o comportamento esperado dos participantes do projeto. Ajudando a criar uma atmosfera social positiva para a comunidade.

Um bom exemplo é o arquivo do [Open Source Guides](https://github.com/Gabrielr2508/opensource.guide/blob/master/CODE_OF_CONDUCT.md). 

Se você tiver alguma sugestão de código de conduta, nos avise, por favor. :)

Não deixe de perguntar se tiver alguma dúvida.

**Comment by gab0gomes** [comment]
Resolvida na #5
