### ISSUE TITLE
Criar CONTRIBUTING.md

### ISSUE THREAD

**Issue by o-leolleo** [Gabrielr2508/recruitment-platform#4]
Essa issue tem a intenção de adicionar ao projeto o arquivo `CONTRIBUTING.md` para deixar claro as regras de contribuição do projeto, bem como esclarecer quaisquer dúvidas.

Um bom exemplo é o arquivo do [Open Source Guides](https://github.com/Gabrielr2508/opensource.guide/blob/master/CONTRIBUTING.md). Claro que adaptações devem ser feitas devido ao escopo do projeto.

Por favor, não deixe de perguntar se tiver alguma dúvida.

**Comment by ricardobarantini** [comment]
Em português ou inglês?

**Comment by gab0gomes** [comment]
Olá, @ricardobarantini. Pode ser em inglês mesmo.

**Comment by gab0gomes** [comment]
Resolvida na #6
